export const techIcons = {
  'HTML': '/icons/html.webp',
  'CSS': '/icons/css.webp',
  'JavaScript': '/icons/javascript.webp',
  'jQuery': '/icons/jquery.webp',
  'React': '/icons/react.webp',
  'Bootstrap': '/icons/bootstrap.webp',
  'Tailwind CSS': '/icons/tailwind.webp',
  'Node.js': '/icons/nodejs.webp',
  'Express': '/icons/express.webp',
  'MySQL': '/icons/mysql.webp',
  'MongoDB': '/icons/mongodb.webp',
  'GraphQL': '/icons/graphql.webp',
  'Sequelize': '/icons/sequelize.webp',
  'Handlebars': '/icons/handlebars.webp',
  'TMDb API': '/icons/api.webp',
  'Watchmode API': '/icons/api.webp',
  'OpenWeather API': '/icons/api.webp',
  'AWS': '/icons/aws.webp',
  'DynamoDB': '/icons/dynamodb.webp',
  'EC2': '/icons/ec2.webp',
  'S3': '/icons/s3.webp',
  'Python': '/icons/python.webp',
  'Flask': '/icons/flask.webp',
  'SQLAlchemy': '/icons/sqlalchemy.webp',
  'Jinja': '/icons/jinja.webp',
  'Gunicorn': '/icons/gunicorn.webp',
  'Redis': '/icons/redis.webp',
  'React Query': '/icons/react-query.webp',
  'SQL': '/icons/sql.webp',
};